apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <html>
      <head><title>ConfigMap Demo</title></head>
      <body style="font-family: sans-serif;">
        <h1>Hola Miriam desde ConfigMap</h1>
        <p>Este contenido viene de un ConfigMap montado como volumen.</p>
      </body>
    </html>
