# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hello-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: hello
#   template:
#     metadata:
#       labels:
#         app: hello
#     spec:
#       containers:
#         - name: hello
#           image: nginx:latest
#           ports:
#             - containerPort: 80
#           env:
#             - name: APP_MESSAGE
#               valueFrom:
#                 configMapKeyRef:
#                   name: hello-config
#                   key: APP_MESSAGE
#             - name: APP_COLOR
#               valueFrom:
#                 configMapKeyRef:
#                   name: hello-config
#                   key: APP_COLOR

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: html-config


